package com.brinsburyanimal.beans;
// Generated 22-Jul-2019 17:44:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BirdMammalRecordId generated by hbm2java
 */
public class BirdMammalRecordId  implements java.io.Serializable {


     private int accommId;
     private Date recordDate;
     private String recordTime;

    public BirdMammalRecordId() {
    }

    public BirdMammalRecordId(int accommId, Date recordDate, String recordTime) {
       this.accommId = accommId;
       this.recordDate = recordDate;
       this.recordTime = recordTime;
    }
   
    public int getAccommId() {
        return this.accommId;
    }
    
    public void setAccommId(int accommId) {
        this.accommId = accommId;
    }
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
    public String getRecordTime() {
        return this.recordTime;
    }
    
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BirdMammalRecordId) ) return false;
		 BirdMammalRecordId castOther = ( BirdMammalRecordId ) other; 
         
		 return (this.getAccommId()==castOther.getAccommId())
 && ( (this.getRecordDate()==castOther.getRecordDate()) || ( this.getRecordDate()!=null && castOther.getRecordDate()!=null && this.getRecordDate().equals(castOther.getRecordDate()) ) )
 && ( (this.getRecordTime()==castOther.getRecordTime()) || ( this.getRecordTime()!=null && castOther.getRecordTime()!=null && this.getRecordTime().equals(castOther.getRecordTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAccommId();
         result = 37 * result + ( getRecordDate() == null ? 0 : this.getRecordDate().hashCode() );
         result = 37 * result + ( getRecordTime() == null ? 0 : this.getRecordTime().hashCode() );
         return result;
   }   


}


