package com.brinsburyanimal.beans;
// Generated 22-Jul-2019 17:44:49 by Hibernate Tools 4.3.1



/**
 * FishRecord generated by hbm2java
 */
public class FishRecord  implements java.io.Serializable {


     private FishRecordId id;
     private Accommodation accommodation;
     private Fed fed;
     private String studentName;
     private Boolean fullClean;
     private Integer ammonia;
     private Integer ph;
     private Integer nitrate;
     private Integer nitrite;
     private Integer calcium;
     private Integer carbonate;
     private Integer phosphate;
     private Integer salt;
     private Integer temp;
     private Integer noFish;
     private Boolean heater;
     private Boolean filterCheck;
     private Boolean lights;
     private Boolean glass;
     private Boolean lid;
     private String comments;

    public FishRecord() {
    }

	
    public FishRecord(FishRecordId id, Accommodation accommodation) {
        this.id = id;
        this.accommodation = accommodation;
    }
    public FishRecord(FishRecordId id, Accommodation accommodation, Fed fed, String studentName, Boolean fullClean, Integer ammonia, Integer ph, Integer nitrate, Integer nitrite, Integer calcium, Integer carbonate, Integer phosphate, Integer salt, Integer temp, Integer noFish, Boolean heater, Boolean filterCheck, Boolean lights, Boolean glass, Boolean lid, String comments) {
       this.id = id;
       this.accommodation = accommodation;
       this.fed = fed;
       this.studentName = studentName;
       this.fullClean = fullClean;
       this.ammonia = ammonia;
       this.ph = ph;
       this.nitrate = nitrate;
       this.nitrite = nitrite;
       this.calcium = calcium;
       this.carbonate = carbonate;
       this.phosphate = phosphate;
       this.salt = salt;
       this.temp = temp;
       this.noFish = noFish;
       this.heater = heater;
       this.filterCheck = filterCheck;
       this.lights = lights;
       this.glass = glass;
       this.lid = lid;
       this.comments = comments;
    }
   
    public FishRecordId getId() {
        return this.id;
    }
    
    public void setId(FishRecordId id) {
        this.id = id;
    }
    public Accommodation getAccommodation() {
        return this.accommodation;
    }
    
    public void setAccommodation(Accommodation accommodation) {
        this.accommodation = accommodation;
    }
    public Fed getFed() {
        return this.fed;
    }
    
    public void setFed(Fed fed) {
        this.fed = fed;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public Boolean getFullClean() {
        return this.fullClean;
    }
    
    public void setFullClean(Boolean fullClean) {
        this.fullClean = fullClean;
    }
    public Integer getAmmonia() {
        return this.ammonia;
    }
    
    public void setAmmonia(Integer ammonia) {
        this.ammonia = ammonia;
    }
    public Integer getPh() {
        return this.ph;
    }
    
    public void setPh(Integer ph) {
        this.ph = ph;
    }
    public Integer getNitrate() {
        return this.nitrate;
    }
    
    public void setNitrate(Integer nitrate) {
        this.nitrate = nitrate;
    }
    public Integer getNitrite() {
        return this.nitrite;
    }
    
    public void setNitrite(Integer nitrite) {
        this.nitrite = nitrite;
    }
    public Integer getCalcium() {
        return this.calcium;
    }
    
    public void setCalcium(Integer calcium) {
        this.calcium = calcium;
    }
    public Integer getCarbonate() {
        return this.carbonate;
    }
    
    public void setCarbonate(Integer carbonate) {
        this.carbonate = carbonate;
    }
    public Integer getPhosphate() {
        return this.phosphate;
    }
    
    public void setPhosphate(Integer phosphate) {
        this.phosphate = phosphate;
    }
    public Integer getSalt() {
        return this.salt;
    }
    
    public void setSalt(Integer salt) {
        this.salt = salt;
    }
    public Integer getTemp() {
        return this.temp;
    }
    
    public void setTemp(Integer temp) {
        this.temp = temp;
    }
    public Integer getNoFish() {
        return this.noFish;
    }
    
    public void setNoFish(Integer noFish) {
        this.noFish = noFish;
    }
    public Boolean getHeater() {
        return this.heater;
    }
    
    public void setHeater(Boolean heater) {
        this.heater = heater;
    }
    public Boolean getFilterCheck() {
        return this.filterCheck;
    }
    
    public void setFilterCheck(Boolean filterCheck) {
        this.filterCheck = filterCheck;
    }
    public Boolean getLights() {
        return this.lights;
    }
    
    public void setLights(Boolean lights) {
        this.lights = lights;
    }
    public Boolean getGlass() {
        return this.glass;
    }
    
    public void setGlass(Boolean glass) {
        this.glass = glass;
    }
    public Boolean getLid() {
        return this.lid;
    }
    
    public void setLid(Boolean lid) {
        this.lid = lid;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


