package com.brinsburyanimal.beans;
// Generated 22-Jul-2019 17:44:49 by Hibernate Tools 4.3.1

import com.brinsburyanimal.dao.AnimalDao;
import com.brinsburyanimal.dao.HealthCheckDao;
import com.brinsburyanimal.dao.SpeciesDao;
import com.brinsburyanimal.util.Utilities;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;




/**
 * HealthCheck generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class HealthCheck  implements java.io.Serializable {


     private HealthCheckId id;
              
     private Animal animal;
     
     private Integer weight;
     private String healthIssue;
     private String treatment;
     private String latinName;
     private String animalName;
     private AnimalId animalId;
     private String commonName;


    public HealthCheck() {
    }
    
    public HealthCheck(Animal animal){
        this.animal = animal;
    }

	
    public HealthCheck(HealthCheckId id, Animal animal) {
        this.id = id;
        this.animal = animal;
    }
    public HealthCheck(HealthCheckId id, Animal animal, Integer weight, String healthIssue, String treatment) {
       this.id = id;
       this.animal = animal;
       this.weight = weight;
       this.healthIssue = healthIssue;
       this.treatment = treatment;
    }
   
    public HealthCheckId getId() {
        return this.id;
    }
    
    public void setId(HealthCheckId id) {
        this.id = id;
    }
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
    public String getHealthIssue() {
        return this.healthIssue;
    }
    
    public void setHealthIssue(String healthIssue) {
        this.healthIssue = healthIssue;
    }
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public String getLatinName() {
        return latinName;
    }

    public void setLatinName(String latinName) {
        this.latinName = latinName;
    }

    public String getAnimalName() {
        return animalName;
    }

    public void setAnimalName(String animalName) {
        this.animalName = animalName;
    }

    public AnimalId getAnimalId() {
        return animalId;
    }

    public void setAnimalId(AnimalId animalId) {
        this.animalId = animalId;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }
    
    
    public List<Species> getAllSpecies(){
        List<Species> species = new ArrayList<>();
        SpeciesDao dao = new SpeciesDao();
        species = dao.getAllSpecies();
        return species;
    }
    
    public String getLatinNameFromCommonName(String commonName){
        List<Species> allSpecies = this.getAllSpecies();
        String currentLatinName = "";
        for (Species eachSpecies: allSpecies){
            if (eachSpecies.getCommonName().equals(commonName)){
                currentLatinName = eachSpecies.getLatinName();
            }
        }
        return currentLatinName;
    }
    
    

   
        
    public List<Animal> getAllAnimals() {
        List<Animal> animals = new ArrayList<Animal>();
        AnimalDao dao = new AnimalDao();
        animals = dao.getAllAnimals();
        return animals;
    }
    
    public String selectAnimal(){
        this.animal = this.findAnimalByName(this.animalName);
        return this.animal.getAnimalName();
    }
    
    public String saveHealthCheck(){
        this.latinName = this.getLatinNameFromCommonName(this.commonName);
        Date date = new Date();
        this.id = new HealthCheckId(this.latinName, this.animalName, date);
        HealthCheckDao dao = new HealthCheckDao();
        dao.saveHealthCheck(this);
        return "WEX";
    }
    
    public Animal getAnimalFromAnimalId(AnimalId animalId){
        List<Animal> allAnimals = new ArrayList<>();
        allAnimals = this.getAllAnimals();
        Animal chosenAnimal = new Animal();
        for(Animal eachAnimal: allAnimals){
            if(eachAnimal.getId().equals(animalId)){
                chosenAnimal = eachAnimal;
            }
        }
        return chosenAnimal;
    }
    
    public Animal findAnimalByName(String selectedName){
        AnimalDao dao = new AnimalDao();
        Animal chosenAnimal = dao.getAnimalByName(selectedName);
        return chosenAnimal;
    }
    
    public List<HealthCheck> getHealthChecksForAnimal(){
        Animal chosenAnimal = this.findAnimalByName(this.animalName);
        HealthCheckDao dao = new HealthCheckDao();
        List<HealthCheck> healthChecks = dao.getHealthChecksForAnimal(chosenAnimal);
        return healthChecks;
    }
    
    public String showHealthChecks(){
        this.latinName = this.getLatinNameFromCommonName(this.commonName);
        List<HealthCheck> healthChecks = this.getHealthChecksForAnimal();
        String result = Utilities.printHealthCheckTable(healthChecks);
        return result;
    }
    
       
    
//    public List<AnimalId> getIdsInArea(String area) {
//        List<AnimalId> ids = new ArrayList<AnimalId>();
//        List<Animal> animals = this.getAllAnimals();
//        for (Animal animal: animals){
//            if (((animal.getAccommodation().getArea().equals(area)))){
//                ids.add(animal.getId());
//            }
//        }
//        return ids;
//    }
//    
//    public List<AnimalId> getAllIds() {
//        List<AnimalId> ids = new ArrayList<AnimalId>();
//        List<Animal> animals = this.getAllAnimals();
//        for (Animal animal: animals){
//                ids.add(animal.getId());
//        }
//        return ids;
//    }
//    
//    public List<String> getNamesInArea(){
//        List<String> names = new ArrayList<String>();
//        List<AnimalId> ids = this.getIdsInArea("#{accommodation.area}");
//        for (AnimalId animalId: ids){
//            names.add(animalId.getAnimalName());
//        }
//        return names;
//    }
//    
//    public List<String> getAllNamesFromId(){
//        List<String> names = new ArrayList<String>();
//        List<AnimalId> ids = this.getAllIds();
//        for (AnimalId animalId: ids){
//            names.add(animalId.getAnimalName());
//        }
//        return names;
//    }
//    
//    public List<String> getAllNames(){
//        List<String> names = new ArrayList<String>();
//        List<Animal> animals = this.getAllAnimals();
//        for (Animal eachAnimal: animals){
//            AnimalId animalId = eachAnimal.getId();
//            names.add(animalId.getAnimalName());
//        }
//        return names;
//    }




}


