package com.brinsburyanimal.beans;
// Generated 22-Jul-2019 17:44:49 by Hibernate Tools 4.3.1



/**
 * HerptileRecord generated by hbm2java
 */
public class HerptileRecord  implements java.io.Serializable {


     private HerptileRecordId id;
     private Accommodation accommodation;
     private Fed fed;
     private String studentName;
     private Boolean fullClean;
     private Boolean water;
     private Integer tempMin;
     private Integer tempMax;
     private Boolean tempReset;
     private Boolean peatMoss;
     private Boolean faeces;
     private Integer humidity;
     private String comments;

    public HerptileRecord() {
    }

	
    public HerptileRecord(HerptileRecordId id, Accommodation accommodation) {
        this.id = id;
        this.accommodation = accommodation;
    }
    public HerptileRecord(HerptileRecordId id, Accommodation accommodation, Fed fed, String studentName, Boolean fullClean, Boolean water, Integer tempMin, Integer tempMax, Boolean tempReset, Boolean peatMoss, Boolean faeces, Integer humidity, String comments) {
       this.id = id;
       this.accommodation = accommodation;
       this.fed = fed;
       this.studentName = studentName;
       this.fullClean = fullClean;
       this.water = water;
       this.tempMin = tempMin;
       this.tempMax = tempMax;
       this.tempReset = tempReset;
       this.peatMoss = peatMoss;
       this.faeces = faeces;
       this.humidity = humidity;
       this.comments = comments;
    }
   
    public HerptileRecordId getId() {
        return this.id;
    }
    
    public void setId(HerptileRecordId id) {
        this.id = id;
    }
    public Accommodation getAccommodation() {
        return this.accommodation;
    }
    
    public void setAccommodation(Accommodation accommodation) {
        this.accommodation = accommodation;
    }
    public Fed getFed() {
        return this.fed;
    }
    
    public void setFed(Fed fed) {
        this.fed = fed;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public Boolean getFullClean() {
        return this.fullClean;
    }
    
    public void setFullClean(Boolean fullClean) {
        this.fullClean = fullClean;
    }
    public Boolean getWater() {
        return this.water;
    }
    
    public void setWater(Boolean water) {
        this.water = water;
    }
    public Integer getTempMin() {
        return this.tempMin;
    }
    
    public void setTempMin(Integer tempMin) {
        this.tempMin = tempMin;
    }
    public Integer getTempMax() {
        return this.tempMax;
    }
    
    public void setTempMax(Integer tempMax) {
        this.tempMax = tempMax;
    }
    public Boolean getTempReset() {
        return this.tempReset;
    }
    
    public void setTempReset(Boolean tempReset) {
        this.tempReset = tempReset;
    }
    public Boolean getPeatMoss() {
        return this.peatMoss;
    }
    
    public void setPeatMoss(Boolean peatMoss) {
        this.peatMoss = peatMoss;
    }
    public Boolean getFaeces() {
        return this.faeces;
    }
    
    public void setFaeces(Boolean faeces) {
        this.faeces = faeces;
    }
    public Integer getHumidity() {
        return this.humidity;
    }
    
    public void setHumidity(Integer humidity) {
        this.humidity = humidity;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


