package com.brinsburyanimal.beans;
// Generated 22-Jul-2019 17:44:49 by Hibernate Tools 4.3.1



/**
 * Slough generated by hbm2java
 */
public class Slough  implements java.io.Serializable {


     private SloughId id;
     private Animal animal;
     private Boolean finished;

    public Slough() {
    }

	
    public Slough(SloughId id, Animal animal) {
        this.id = id;
        this.animal = animal;
    }
    public Slough(SloughId id, Animal animal, Boolean finished) {
       this.id = id;
       this.animal = animal;
       this.finished = finished;
    }
   
    public SloughId getId() {
        return this.id;
    }
    
    public void setId(SloughId id) {
        this.id = id;
    }
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }
    public Boolean getFinished() {
        return this.finished;
    }
    
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }




}


