package com.brinsburyanimal.beans;
// Generated 22-Jul-2019 17:44:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SloughId generated by hbm2java
 */
public class SloughId  implements java.io.Serializable {


     private String latinName;
     private String animalName;
     private Date recordDate;

    public SloughId() {
    }

    public SloughId(String latinName, String animalName, Date recordDate) {
       this.latinName = latinName;
       this.animalName = animalName;
       this.recordDate = recordDate;
    }
   
    public String getLatinName() {
        return this.latinName;
    }
    
    public void setLatinName(String latinName) {
        this.latinName = latinName;
    }
    public String getAnimalName() {
        return this.animalName;
    }
    
    public void setAnimalName(String animalName) {
        this.animalName = animalName;
    }
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SloughId) ) return false;
		 SloughId castOther = ( SloughId ) other; 
         
		 return ( (this.getLatinName()==castOther.getLatinName()) || ( this.getLatinName()!=null && castOther.getLatinName()!=null && this.getLatinName().equals(castOther.getLatinName()) ) )
 && ( (this.getAnimalName()==castOther.getAnimalName()) || ( this.getAnimalName()!=null && castOther.getAnimalName()!=null && this.getAnimalName().equals(castOther.getAnimalName()) ) )
 && ( (this.getRecordDate()==castOther.getRecordDate()) || ( this.getRecordDate()!=null && castOther.getRecordDate()!=null && this.getRecordDate().equals(castOther.getRecordDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLatinName() == null ? 0 : this.getLatinName().hashCode() );
         result = 37 * result + ( getAnimalName() == null ? 0 : this.getAnimalName().hashCode() );
         result = 37 * result + ( getRecordDate() == null ? 0 : this.getRecordDate().hashCode() );
         return result;
   }   


}


